org: alyalo
app: test
service: test-progect2
frameworkVersion: "3"

plugins:
  - serverless-esbuild

custom:
  tableName: "categoreis-table-${sls:stage}"
  esbuild:
    bundle: true
    concurrency: 10
    minify: false
    packager: npm
    watch:
      pattern: ["**/*.js"]

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - lambda:*
          Resource: "*"
  environment:
    AWS_PROVIDER_REGION: ${self:provider.region}
    CATEGORIES_TABLE: ${self:custom.tableName}
    EVENT_BUS_NAME: event-bus-${sls:stage}
    EVENT_BUS_SERVICE_SOURCE: ${self:org}.${self:service}

functions:
  getCategories:
    events:
      - httpApi: "GET /categories/{categoryId}"
    handler: src/category-get/handler.default
    memorySize: 256
  createCategories:
    events:
      - httpApi: "POST /categories"
    handler: src/category-create/handler.default
    memorySize: 256

resources:
  Resources:
    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: categoryId
            AttributeType: S
        KeySchema:
          - AttributeName: categoryId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: event-bus-${sls:stage}

outputs:
  eventBusArn: !GetAtt EventBus.Arn
