org: alyalo
app: test
service: test-project
frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  tableNamePost: "posts-tbl-${sls:stage}"
  esbuild:
    bundle: true
    concurrency: 10
    minify: false
    packager: npm
    watch:
      pattern: ["**/*.js"]

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - lambda:*
          Resource:
            - Fn::GetAtt: [PostsTable, Arn]
  environment:
    POSTS_TABLE: ${self:custom.tableNamePost}

functions:
  getPosts:
    events:
      - httpApi: "GET /posts/{categoryId}"
    handler: src/post-get/handler.default
    memorySize: 256
  createFirstPosts:
    handler: src/first-post-create/handler.default
    events:
      - eventBridge:
          eventBus: ${output:test-progect2.eventBusArn}
          pattern:
            source:
              - ${self:org}.test-progect2
            detail-type:
              - createWelcomePost
    memorySize: 256
  createPosts:
    events:
      - httpApi: "POST /posts"
    handler: src/post-create/handler.default
    memorySize: 256

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: categoryId
            AttributeType: S
          - AttributeName: creationDate
            AttributeType: S
        KeySchema:
          - AttributeName: categoryId
            KeyType: HASH
          - AttributeName: creationDate
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNamePost}
