org: alyalo
app: test
service: test-project
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-esbuild

custom:
  tableNamePost: 'posts-tbl-${sls:stage}'
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ PostsTable, Arn ]
  environment:
    POSTS_TABLE: ${self:custom.tableNamePost}

functions:
  api:
    handler: handler.default
    events:
      - httpApi: '*'

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: categoryId
            AttributeType: S
          - AttributeName: creationDate
            AttributeType: S
        KeySchema:
          - AttributeName: categoryId
            KeyType: HASH
          - AttributeName: creationDate
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNamePost}
